services:
  - type: web
    name: flixhd-premium-bot
    runtime: python
    rootDir: bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_CHANNEL_ID
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: UPI_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: SELF_PING_URL
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
